install/uninstall process improvements
AsimovMac/asimov pull request #35
Opened 2019-01-29 16:41 UTC by sylv3r

I have improved the install process and added an uninstall script, all of these managed by a Makefile.
I have also added a TODO for what I was thinking could be some checks/improvements if I or anyone has the time to work on it.

Hope it will helps, cheers.

2019-02-02 02:54 UTC, stevegrunwell requested changes
I had never considered the Makefile route, but for a system-level utility that makes a lot of sense!

I've left a couple notes, but overall this is looking great from a code perspective!

2019-02-02 02:54 UTC, stevegrunwell commented on README.md
> +* [optional] before installing, you can edit `com.stevegrunwell.asimov.plist` to change the scheduling of Asimov (default to once a day)
A bit of editing here:

* "[Optional]" should be capitalized
* Sentences should end in appropriate punctuation
* "Run `make` to automatically:"

2019-02-02 02:54 UTC, stevegrunwell commented on TODO.md
> +# TODO
I tend to create todo files as well, but these are items better tracked in GitHub issues rather than a file that's living in the repository.

2019-02-10 02:01 UTC, sylv3r commented
@stevegrunwell Thanks for your interest in my PR.
I've updated it following your notes.

I just have one issue : I'm unable to figure out how to pass your `spellcheck` test using an external sourcing vars file.

2026-07-26 12:57 UTC, django23 commented
@sylver this is in — thank you, and sorry it took so long to land. 🙏

Your work shipped in v0.4.0 and is part of v0.10.0: `make install` / `make uninstall` targets,
a proper `scripts/uninstall.sh`, and the interval reference comments in the plist. You're
credited in the CHANGELOG.

Closing as integrated (the code moved enough that it went in by hand rather than as a merge). 🎉

2026-07-26 12:57 UTC, closed without merging

2026-07-26 21:03 UTC, sylver commented
> sorry it took so long to land. 🙏

<img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNnphc2xqc213NzBxdGFlcDFmdDJuZTJxazdiN2NmdmFidTBnMG16aSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/FoH28ucxZFJZu/giphy.gif" />

;)