Exclude derived data folders from from xcdoe
AsimovMac/asimov pull request #64
Opened 2020-12-19 16:51 UTC by mdab121

2020-12-20 16:11 UTC, j-f1 commented on tests/AsimovTest.php
> +            'XCode'     => ['DerivedData', 'DerivedData'],
```suggestion
            'Xcode'     => ['DerivedData', 'DerivedData'],
```

2020-12-20 16:11 UTC, j-f1 commented on asimov
> +    'DerivedData DerivedData'     # XCode (Swift)
```suggestion
    'DerivedData DerivedData'     # Xcode (Swift)
```

2020-12-20 21:07 UTC, stevegrunwell approved these changes
Thank you for the addition!

2020-12-20 21:29 UTC, stevegrunwell requested changes
The tests failing here made me dig deeper, and I'm hoping someone with Xcode experience can help provide context.

[From what I've read](https://stackoverflow.com/questions/13761934/xcode-derived-data-location), Xcode will store build artifacts in the `DerivedData/` directory, and this is usually(?) at a system-wide level (e.g. `~/Library/Developer/Xcode/DerivedData`) — is this correct? If so, Asimov would be better-served blocking that directory.

As it stands now, the code in this PR tells Asimov "Look for a `DerivedData` directory that sits adjacent to...itself", which seems like a roundabout way of saying "Block all `DerivedData` directories from Time Machine backups. However, that runs counter to Asimov's more conservative "make sure there's a matching dependency file so we don't block anything accidentally" ethos.

Granted, "DerivedData" seems very unlikely to be anything else on a developer's machine (save for perhaps some Swift developer's musical side-project), but I'd like to better understand this directory before including it in Asimov, please.

2020-12-22 11:18 UTC, mdab121 commented
Hey!

Thanks for the response. You're right, that the `DerivedData` folder (which is basically build artifacts, indexes, etc) are located at `~/Library/Developer/Xcode/DerivedData` by default.

However it's very common to have it in the project directory. I do that as an iOS developer, and I know many other devs that do. That's why it's also listed in the default [`.gitignore` for XCode](https://www.toptal.com/developers/gitignore/api/xcode).

It's really a time machine killer, because these tend to be ~1GB even for a simple XCode project.

---

What i can suggest is to make it conditional to exclude `DerivedData` unless an XCode project file exists in the directory? Which would be anything like `*.xcodeproj`.

2020-12-30 02:57 UTC, stevegrunwell commented
> What i can suggest is to make it conditional to exclude `DerivedData` unless an Xcode project file exists in the directory? Which would be anything like `*.xcodeproj`.

I think that makes the most sense, but it'll require refactoring [how the `find` command is utilized within Asimov](https://github.com/stevegrunwell/asimov/blob/develop/asimov#L89), as `test -e` checks for the existence of a file, but doesn't account for wildcards.

We want to make sure that whatever we do here is still performant, but adding wildcard support would open up some opportunities.

2026-07-26 12:58 UTC, django23 commented
@mdab121 this landed — thank you! 🎉

Both halves of it shipped in v0.4.0: glob support in sentinel definitions, and `DerivedData *.xcodeproj` built on top of it. The glob support turned out to be the gift that kept giving — `bin *.csproj`, `obj *.fsproj` and friends all rely on it now.

Credited in the CHANGELOG. Closing as integrated. 🙏

2026-07-26 12:58 UTC, closed without merging